name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'  # Updated Node.js version for Next.js compatibility

      - name: Install dependencies
        run: npm install

      - name: Build and export project
        # Use SKIP_ESLINT to disable ESLint during the build process
        run: SKIP_ESLINT=true npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
